services:
  db:
    image: postgres:18-alpine
    container_name: academia-erp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: academiaerp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academia-erp-api
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgrespasswd@db:5432/academiaerp
      JWT_SECRET: f081f446-3080-405a-a58c-5a57d3b86404
      CORS_ORIGIN: http://localhost:5173,http://localhost:5174
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWD: ChangeMe123!
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
